# 项目的启动端口
server:
  port: 20000
  error:
    include-message: always

spring:
  application:
    # 定义项目名称
    name: coupon-template-serv
  datasource:
    # 数据源
    username: coupon
    password: coupon
    url: jdbc:postgresql://1.13.2.185:15432/postgres
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    # 连接池
    hikari:
      pool-name: GeekbangCouponHikari
      connection-timeout: 5000
      idle-timeout: 30000
      maximum-pool-size: 10
      minimum-idle: 5
      max-lifetime: 60000
      auto-commit: true
  jpa:
    show-sql: true
    hibernate:
      # 在生产环境全部为none，防止ddl结构被自动执行
      ddl-auto: none
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/coupon/liquibase.xml

logging:
  level:
    com.broadview.coupon: debug
