apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels:
    app: tomcat
spec:
  selector:
    matchLabels:
      app: tomcat
  replicas: 3
  template:
    metadata:        
      labels:
        app: tomcat
    spec:
      containers:
      - name: tomcat
        image: tomcat:9.0
        imagePullPolicy: Always 
        livenessProbe:   
          tcpSocket:
            port: 8080
          initialDelaySeconds: 60
          timeoutSeconds: 30
          successThreshold: 1
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5          
        lifecycle:
          preStop:
            exec:
              command:
              - sleep
              - "10"
        ports:
        - name: http
          containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-svc
  labels:
    app: tomcat
spec:
  type: NodePort
  ports:  
  - port: 8080
    targetPort: 8080
    nodePort: 31111 #The range of valid ports is 30000-32767
    protocol: TCP
    name: http-web-svc
  selector:
    app: tomcat
